- id: doi:10.1145/3522579
  type: paper
  tags:
    - metrics
    - survey
    - self-assessment
    
#- id: doi:10.5555/3306127.3331842
#  type: paper

- id: doi:10.3389/frobt.2021.674292
  type: paper
  tags:
    - tool use
    - co-creativity
    - learning from corrections

- id: doi:10.1016/j.artint.2021.103551
  type: paper
  tags:
    - task representations
    - abstraction

- id: doi:10.1007/978-3-319-24586-7_9
  type: paper

- id: doi:10.1145/3277905
  type: paper
  tags:
    - tool use
    - learning from corrections
    
- id: doi:10.24963/ijcai.2021/599
  type: paper
  tags:
    - human-in-the-loop
    - survey
    - human factors
    
- id: url:https://iqr.cs.yale.edu/pdf/fitzgerald-corl22-inquire.pdf
  title: "INQUIRE: INteractive Querying for User-aware Informative REasoning"
  authors:
    - Tesca Fitzgerald
    - Pallavi Koppol
    - Patrick Callaghan
    - Russell Q Wong
    - Reid Simmons
    - Oliver Kroemer
    - Henny Admoni
  publisher: Conference on Robot Learning
  date: "2022-12-14"
  type: paper
  tags:
    - inverse reinforcement learning
    - learning from demonstrations
    - learning from corrections
    
- id: url:https://iqr.cs.yale.edu/pdf/karli-fitzgerald-langrob23-ambiguities.pdf
  title: Resolving Ambiguities in LLM-enabled Human-Robot Collaboration
  authors:
    - Ulas Berk Karli
    - Tesca Fitzgerald
  publisher: CoRL Workshop on Language and Robot Learning
  date: "2023-11-06"
  type: paper  
  tags:
    - LLMs
    - ambiguity
    - self-assessment
    
- id: url:https://iqr.cs.yale.edu/pdf/wang-fitzgerald-hirl24-legibility.pdf
  title: Legibility-Aware Learning from Corrections
  authors:
    - Anjiabei Wang
    - Tesca Fitzgerald
  publisher: HRI Workshop on Human-Interactive Robot Learning
  date: "2024-03-15"
  type: paper
  tags:
    - learning from corrections
    - inverse reinforcement learning
    - legibility
    - user study

- id: url:https://iqr.cs.yale.edu/pdf/potdar-fitzgerald-ss4hri24-crm.pdf
  title: Toward Enabling Crew Resource Management Objectives in Human-Robot Collaboration in Safety-Critical Situations
  authors:
    - Anushka Potdar
    - Tesca Fitzgerald
  publisher: HRI Workshop on Social Signal Modeling in Human-Robot Interaction
  date: "2024-03-11"
  type: paper
  tags:
    - mental models
    - human-robot teaming
    
- id: url:https://iqr.cs.yale.edu/pdf/wang-scassellati-fitzgerald-leap24-competency.pdf
  title: Toward Measuring the Effect of Robot Competency on Human Kinesthetic Feedback in Long-Term Task Learning
  authors:
    - Shuangge Wang
    - Brian Scassellati
    - Tesca Fitzgerald
  publisher: HRI Workshop on Lifelong Learning and Personalization in Long-Term Human-Robot Interaction (LEAP-HRI)
  date: "2024-03-11"
  type: paper
  tags:
    - inverse reinforcement learning
    - learning from corrections
    - user study
