- id: doi:10.1145/3568162.3576964
  type: paper
  title: |-
    'What If It Is Wrong': Effects of Power Dynamics and Trust Repair Strategy on Trust and Compliance in HRI
  # Needs custom title since the double quotation marks mess up the HTML rendering

- id: doi:10.1145/3522579
  type: paper

- id: doi:10.3389/frobt.2021.674292
  type: paper

- id: doi:10.1016/j.artint.2021.103551
  type: paper

- id: doi:10.1145/3277905
  type: paper

- id: doi:10.24963/ijcai.2021/599
  type: paper

- id: doi:10.1007/978-3-319-24586-7_9
  type: paper

- title: Legibility-Aware Learning from Corrections
  authors:
    - Anjiabei Wang
    - Tesca Fitzgerald
  publisher: HRI Workshop on Human-Interactive Robot Learning
  date: 2024-03-15
  link: research/wang-fitzgerald-hirl24-legibility.pdf
  type: paper

# Errors for some reason
# - id: doi:10.5555/3306127.3331842
#   type: paper
# - id: doi:10.5555/2906831.2906869
#   type: paper
